<?xml version="1.0" ?>
<xsl:stylesheet version="1.0"
				xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:wi="http://schemas.microsoft.com/wix/2006/wi"
                xmlns:msxsl="urn:schemas-microsoft-com:xslt"
                xmlns:xv="http://custom.com/">

	<xsl:output encoding="UTF-8" indent="yes" method="xml" />
	<msxsl:script language="JScript" implements-prefix="xv">
	<![CDATA[
	// post-processes file ids to conform to conventions:
	
	function hackFileId( id) {
		return id;   
		//.replace("_x64_", "_AMD64_");   
	}
	]]>
	</msxsl:script>
  
	<!-- IdentityTransform -->
	<xsl:template match="/ | @* | node()">
	<xsl:copy>
		<xsl:apply-templates select="@* | node()" />
	</xsl:copy>
	</xsl:template>
	
	<xsl:template match="wi:File[contains(@Source, '.exe') or contains(@Source,'.cmd')]">
	<xsl:copy>
		<xsl:apply-templates select="@*"/>
		<xsl:attribute name="Id">
		<!-- replace Id from autogenerated bs to a meaningful and predictable name -->   
		<xsl:value-of select="xv:hackFileId(
					concat('File_', 
					translate(
						substring-after(@Source, '\'),
						'\-', '__')                    
					))"/> 
		</xsl:attribute>
		<xsl:apply-templates select="node()" />
	</xsl:copy>
	</xsl:template>
	
</xsl:stylesheet>